---
title: "Week11_Join_Exercises"
author: "Nilay Kamar"
date: "12/01/2019"
output: 
  html_document: 
    df_print: default
    toc: yes
---

```{r cars}
library(tidyverse)
library(knitr)

load("/Users/nilaykamar/Downloads/atp_tennis_data_2017.RData")
```

## Task 1: Rank countries(Flag codes) by the single champions

```{r fig.align='left'}
library(knitr)
single_champions_countries <- tourney_df %>% left_join(., player_df, by = c("singles_winner_player_id" = "player_id")) %>%
  count(flag_code, sort = TRUE)

kable(head(single_champions_countries))

```

## Task 2: Rank countries which did not get only singles champions by the sets won whom they win the match.

```{r fig.align='left'}
library(knitr)
not_champions_players <- player_df %>% select(player_id, flag_code) %>% anti_join(., single_champions_countries) 

not_champions_players %>% left_join(., score_df, by=c("player_id"="winner_player_id")) %>%
  group_by(flag_code) %>%
  summarise(total_won = sum(winner_games_won, na.rm = TRUE)) %>%
  arrange(desc(total_won))

kable(head(not_champions_players))

```

## Task 3: Rank countries of players who have made no fault

```{r, fig.align='left'}
library(knitr)
no_fault <- stats_df %>% select(match_id, winner_double_faults) %>% filter(winner_double_faults == 0)

player_score <- score_df %>% select(match_id, winner_player_id)

no_fault_players <- no_fault %>% inner_join(., player_score, by = c("match_id"))

no_fault_countries <- no_fault_players %>% left_join(., player_df, by = c("winner_player_id" = "player_id")) %>%
  count(flag_code, sort = TRUE)

kable(head(no_fault_countries))

```

## Task 4: Rank players who have never break in matches by match duration, adding country 

```{r fig.align='left'}
library(knitr)
no_break_match <- stats_df %>% select(match_id, winner_break_points_saved, match_duration) %>% filter(winner_break_points_saved != 0)
countries_player <- player_df %>% select(player_id, player_slug, flag_code)

no_break_players <- no_break_match %>% left_join(., player_score, by = c("match_id")) %>%
  group_by(winner_player_id) %>%
  summarise(total_duration = sum(match_duration, na.rm = TRUE)) %>%
  left_join(., countries_player, by = c("winner_player_id" = "player_id")) %>%
  arrange(desc(total_duration))

kable(head(no_break_players))
```





